### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by defagos**
Hi!

I have added the ability to add the iOS comScore library using [Carthage](https://github.com/Carthage/Carthage). The only required work was to create an Xcode project with a dynamic framework target and a shared scheme.

The version number has been set in the framework `Info.plist` file. This file needs to be updated when the library version changes. The Xcode project also needs to be updated if public headers are altered.

Best regards.

### CODE REVIEW

**Comment by raspu** [comment]
Hi Samuel, Thank you very much for this! 

One question, what is the reason you decided to disable bitcode?

**Comment by defagos** [comment]
I had checked the comScore static library for a bitcode section, but incorrectly (and thus found none). This is why I had disabled bitcode for the framework target.

I was wrong, bitcode is now enabled again.

Thanks!

**Comment by raspu** [comment]
Merged! Thanks for your spending your time on this :).

**Comment by aechap02** [comment]
I think there may be an issue with shared scheme, I'm getting an error:

`*** Skipped building ComScore-iOS-SDK due to the error:
Dependency "ComScore-iOS-SDK" has no shared framework schemes`

My cartfile is using:
`github "comScore/ComScore-iOS-SDK"`

**Comment by veeamd** [comment]
I have the same issue as @aechap02

**Comment by veeamd** [comment]
@aechap02  I forked the repository and upgraded to XCode 8 recommended settings, now the error is gone.

**Comment by veeamd** [comment]
@raspu Can you guys check if the XCode not upgrading to XCode8 is the problem? If so can you guys update the profile file? 
Thanks

**Comment by raspu** [comment]
Sure, give me a couple of days. And sorry for the delay guys.

**Comment by raspu** [comment]
Hi guys, sorry again for the delay. We have been busy working on a new release that is going live today. This new version comes with major changes and we didn’t have the time to ship it with Carthage support, so we are dropping it for now. We are going to revisit this in the future, but we are always open to your PRs if you need this faster. 

We are also moving to a [new repo](https://github.com/comScore/ComScore-iOS-watchOS-tvOS), therefore we are deprecating this repo.

**Pull request merged**
